# Generated by Django 5.2.6 on 2025-09-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='document',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
    ]
