# Generated by Django 5.2.6 on 2025-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_hours',
            field=models.TimeField(null=True),
        ),
    ]
