# Generated by Django 5.2.6 on 2025-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='working_hours',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
